config/routes.rb
Rails.application.routes.draw do
  
  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/edit'
  # get 'journals/index'
  # get 'journals/show'
  # get 'journals/new'
  # get 'journals/edit'

  


  # root to: 'users/sign_in'

  

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  devise_for :users

  
  resources :journals
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :journals
    belongs_to :user
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :journals
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    journals_path # your path
  end
  
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]
  

  def index
    @categories = current_user.categories
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = current_user.categories.new
  end

  def create
    @category = current_user.categories.new(category_params)


    if @category.save
      redirect_to @category
    else 
      render :new
    end
  end

  def edit
    @category = Category.new
  end

  def update 
    @category = Category.find(params[:id])
    
    if @category.update(category_params)
      redirect_to @category
    else
      render edit
    end
  end

  def destroy
    @category = Category.find(params[:id])

    @category.destroy
    redirect_to @category
  end

  def correct_user
    @category = current_user.categories.find_by(id: params[:id])
    redirect_to category_path, notice: "Not Authorize" if @category.nil?
  end  

  private 

  def category_params
    params.require(:category).permit(:name, :description, :user_id)
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @categories = current_user.categories

    cate = params[:cate]
    date = params[:date]

    if !date.nil?
      @journals = Journal.where(:deadline => date)
    else
      @journals = current_user.journals
    end

    if !cate.nil?
      @journals = Journal.where(:category_id => cate)
    else
      @journals = current_user.journals
    end
  end

  def show
    @journal = Journal.find(params[:id])
  end

  def new
    # @journal = Journal.new
    @journal = current_user.journals.new
  end
  
  def create 
    @journal = current_user.journals.new(journal_params)
    # @journal = current_user.journals.build(journal_params)


    if @journal.save
      redirect_to @journal
    else 
      render :new
    end
  end

  def edit
    @journal = Journal.find(params[:id])
  end

  def update 
    @journal = Journal.find(params[:id])
    
    if @journal.update(journal_params)
      redirect_to @journal
    else
      render edit
    end
  end

  def destroy
    @journal = Journal.find(params[:id])

    @journal.destroy
    redirect_to @journal
  end

  def correct_user
    @journal = current_user.journals.find_by(id: params[:id])
    redirect_to journal_path, notice: "Not Authorize" if @journal.nil?
  end


  private 

  def journal_params
    params.require(:journal).permit(:title, :content, :category_id, :user_id, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/today_helper.rb
module TodayHelper
end

app/views/categories/_form.html.erb
<div class="flex-row d-flex justify-content-center">

  <div class="col-md-8">
    <div class="card mt-5">
      <div class="card-body">
        <h1 style="text-align:center; color: blue;">Category new</h1>
        <%= form_with model: @category, local: true do |f|%>
        <div class="form-group mb-3">
          <%= f.label :name%>
          <%= f.text_field :name, class: 'form-control'%>
        </div>
        <div class="form-group mb-3">
          <%= f.label :description%>
          <%= f.text_area :description, class: 'form-control'%>
        </div>
        <div class="form-group mb-3">
          <%= f.number_field :user_id, id: :category_user_id, value: current_user.id, type: :hidden, class: 'form-control'%>
        </div>
          <%= f.submit "Create Category", class: 'btn btn-outline-primary'%>
          <%= link_to "Back", categories_path, class: 'btn btn-outline-secondary' %>
        <% end  %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Categories edit</h1>


<%= render 'form' %>

app/views/categories/index.html.erb
<div class="flex-row d-flex justify-content-center">

<h1>Categories index</h1>

  <div class="col-md-8">
    <div class="card mt-5">
      <div class="card-body">
        <% @categories.each do |category| %>
          <div class="form-group mb-3">
            <h3><%= link_to category.name, category_path(category.id) %></h3>
          </div>
        <% end %>
        <div class="form-group mb-3">
          <%= link_to "Create Category", new_category_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<h1>Categories show</h1>

<h3><%= @category.name %></h3>

<p><%= @category.description %></p>


<%= link_to "Edit", edit_category_path(@category.id) %>
<%= link_to "Delete", category_path(@category.id), method: :delete %>
<%= link_to "Back", categories_path %>

app/views/journals/_form.html.erb
<div class="flex-row d-flex justify-content-center">

  <div class="col-md-8">
    <div class="card mt-5">
      <div class="card-body">
        <%= form_with model: @journal, local: true do |f|%>

        <div class="form-group mb-3">
          <%= f.label :title%>
          <%= f.text_field :title, class: 'form-control'%>
        </div>

        <div class="form-group mb-3">
          <%= f.label :content%>
          <%= f.text_area :content, class: 'form-control'%>
        </div>

        <div class="form-group mb-3">  
          <%= f.label 'Category' %>
          <%= f.select :category_id, current_user.categories.map {|c|[c.name, c.id]}, {}, { class: 'form-select form-select-md mb-3'} %>
        </div>

        <div class="form-group mb-3">  
          <%= f.number_field :user_id, id: :journal_user_id, value: current_user.id, type: :hidden %>
        </div>
        <div class="form-group mb-3">  
          <%= f.label 'Deadline' %>
          <%= f.date_field :deadline, class: 'form-control'  %>
        </div>

          <%= f.submit "Create Journal", class: 'btn btn-outline-primary' %>
          <%= link_to "Back", journals_path, class: 'btn btn-outline-secondary' %>
        <% end  %>
      </div>
    </div>
  </div>
 
  
</div>

app/views/journals/edit.html.erb
<h1 class="text-center">Edit</h1>


<%= render 'form' %>

app/views/journals/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-8">
      <div class="row">   
      
        <% @journals.each do |journal| %>
        <div class="col-md-6">
          <div class="card mt-3">
            <div class="card-body">
              <h3><%= link_to journal.title, journal_path(journal.id), class: 'text-info' %></h3>
              
              <%= link_to "View", journal_path(journal.id), class: 'btn btn-info text-light' %>
            </div>
          </div>
        </div>
        <% end %>
      </div>  
    </div>

    <div class="col-md-4">

      <div class="card mt-3">
        <div class="card-header">
          Categories
        </div>

        <div class="card-body">
          <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= link_to "All", journals_path %>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= link_to "Today", journals_path(:date => Date.today) %>
            </li>
            <% @categories.each do |category| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <%= link_to category.name, journals_path(:cate => category.id) %>
                <span class="badge bg-primary rounded-pill"><%= category.journals.count%></span>
              </li>
            <% end %>
          </ul>
          

          
        </div>
      </div>
      
    </div>

  </div>
</div>


  

app/views/journals/new.html.erb
<%= render 'form' %>

app/views/journals/show.html.erb
<div class="container-fluid mt-3">
 
  <h1>Category: <%= @journal.category.name %></h1>
   <h3><%= @journal.title %></h3>
  <p><%= @journal.content %></p>
</div>


<%= link_to "Edit", edit_journal_path(@journal.id), class: 'btn btn-primary' %>
<%= link_to "Delete", journal_path(@journal.id), method: :delete, class: 'btn btn-danger' %>
<%= link_to "Back", journals_path, class: 'btn btn-secondary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AvionJournalProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# <p class="notice"><%= notice </p> 
    <p class="alert"><%= alert </p> %>

    <% if user_signed_in? %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Journal With Categories</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-md-auto mb-2 mb-lg-0">
         
            <li class="nav-item p-2">
              <%= link_to "Create Journal", new_journal_path, class: 'nav-link btn btn-outline-success' %>
            </li>
            <li class="nav-item p-2">
              <%= link_to "Create Categories", new_category_path, class: 'nav-link btn btn-outline-success' %>
            </li>
            <li class="nav-item p-2">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link btn btn-outline-danger' %>
            </li>
          
          </ul>
        </div>
      </div>
    </nav>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p>
    <% else %>
      <p class="notice"><%= notice %></p> 
      <p class="alert"><%= alert %></p>
    <% end%>

    <%= yield %>
  </body>
</html>